### ISSUE TITLE
PHP Fatal error runinseparate process

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-search_elastic#97]
Moodle MOODLE_402_STABLE
elastic MOODLE_310_STABLE
PHP8.0

```
PHP Fatal error:  Uncaught coding_exception: Coding error detected, it must be fixed by a programmer: When including this file for a unit test, the test must be run in an isolated process. See the PHPUnit @runInSeparateProcess and @runTestsInSeparateProcesses annotations. in /var/www/html/lib/setuplib.php:2204
    Stack trace:
    #0 /var/www/html/lib/externallib.php(35): require_phpunit_isolation()
    #1 /var/www/html/search/engine/elastic/externallib.php(26): require_once('/var/www/html/l...')
    #2 /var/www/html/search/engine/elastic/tests/externallib_test.php(33): require_once('/var/www/html/s...')
    #3 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/var/www/html/s...')
    #4 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/html/s...')
    #5 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(397): PHPUnit\Util\FileLoader::checkAndLoad('/var/www/html/s...')
    #6 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(527): PHPUnit\Framework\TestSuite->addTestFile('/var/www/html/s...')
    #7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles(Array)
    #8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(391): PHPUnit\TextUI\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
    #9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments(Array)
    #10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
    #11 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
    #12 /var/www/html/vendor/bin/phpunit(122): include('/var/www/html/v...')
    #13 {main}
  
    Next PHPUnit\TextUI\RuntimeException: Coding error detected, it must be fixed by a programmer: When including this file for a unit test, the test must be run in an isolated process. See the PHPUnit @runInSeparateProcess and @runTestsInSeparateProcesses annotations. in /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php:99
    Stack trace:
    #0 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
    #1 /var/www/html/vendor/bin/phpunit(122): include('/var/www/html/v...')
    #2 {main}
      thrown in /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php on line 99
  stderr_lines: <omitted>
  stdout: |-
    Compose v2 is not available in Docker CLI, falling back to use docker-compose script
    Moodle 4.2+ (Build: 20230526), 6c9d8e17ddcdceb4bcb0c7db23b39ff3b01c624a
    Php: 8.0.28, mysqli: 8.0.33, OS: Linux 5.15.73-45.135.amzn2022.x86_64 x86_64
  
    Fatal error: Uncaught coding_exception: Coding error detected, it must be fixed by a programmer: When including this file for a unit test, the test must be run in an isolated process. See the PHPUnit @runInSeparateProcess and @runTestsInSeparateProcesses annotations. in /var/www/html/lib/setuplib.php:2204
    Stack trace:
    #0 /var/www/html/lib/externallib.php(35): require_phpunit_isolation()
    #1 /var/www/html/search/engine/elastic/externallib.php(26): require_once('/var/www/html/l...')
    #2 /var/www/html/search/engine/elastic/tests/externallib_test.php(33): require_once('/var/www/html/s...')
    #3 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/var/www/html/s...')
    #4 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/html/s...')
    #5 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(397): PHPUnit\Util\FileLoader::checkAndLoad('/var/www/html/s...')
    #6 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(527): PHPUnit\Framework\TestSuite->addTestFile('/var/www/html/s...')
    #7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles(Array)
    #8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(391): PHPUnit\TextUI\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
    #9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments(Array)
    #10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
    #11 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
    #12 /var/www/html/vendor/bin/phpunit(122): include('/var/www/html/v...')
    #13 {main}
  
    Next PHPUnit\TextUI\RuntimeException: Coding error detected, it must be fixed by a programmer: When including this file for a unit test, the test must be run in an isolated process. See the PHPUnit @runInSeparateProcess and @runTestsInSeparateProcesses annotations. in /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php:99
    Stack trace:
    #0 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
    #1 /var/www/html/vendor/bin/phpunit(122): include('/var/www/html/v...')
    #2 {main}
      thrown in /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php on line 99
```

**Comment by dmitriim** [comment]
This has been fixed
